version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: